__include__: ["Dome-M-AITOD.yml"]

output_dir: ./output/dome_m_custom

postprocessor: CustomPostProcessor

DomeTransformer:
  min_num_select: 100
  max_num_select: 100

HybridEncoder:
  mwas_window_size: 8

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000005
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.000005
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.00005
  betas: [0.9, 0.999]
  weight_decay: 0.0001

lr_scheduler:
  type: MultiStepLR
  milestones: [200, 260]
  gamma: 0.5


# Increase to search for the optimal ema
epoches: 300
eval_spatial_size: [1024, 1024]

train_dataloader:
  dataset:
    img_folder: "C:/Shijie_Li/boat_detection/code/data/images/train"
    ann_file: "C:/Shijie_Li/boat_detection/code/data/annotations/train_coco.json"
    transforms:
      ops:
        - { type: RandomPhotometricDistort, p: 0.5 }
        - { type: RandomZoomOut, fill: 0 }
        - { type: RandomIoUCrop, p: 0.8 }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: RandomHorizontalFlip }
        - { type: Resize, size: [ 1024, 1024 ], }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: ConvertPILImage, dtype: 'float32', scale: True }
        - { type: ConvertBoxes, fmt: 'cxcywh', normalize: True }
      policy:
        epoch: 200
  collate_fn:
    base_size: 1024
    base_size_repeat: 4
    stop_epoch: 200
    ema_restart_decay: 0.9999


val_dataloader:
  num_workers: 0
  dataset:
    transforms:
      ops:
        - { type: Resize, size: [ 1024, 1024 ], }
        - { type: ConvertPILImage, dtype: 'float32', scale: True }
    img_folder: "C:/Shijie_Li/boat_detection/code/data/images/train"
    ann_file: "C:/Shijie_Li/boat_detection/code/data/annotations/train_coco.json"
